algo = input('Digite algo: ')
print(f'Esse tipo de variável é{type(algo)}')
print(f'{algo} é um valor númerico? {algo.isnumeric()}')
print(f'{algo} é um valor alfabético? {algo.isalpha()}')
print(f'{algo} é um valor alfanúmerico? {algo.isalnum()}')
print(f'{algo} é um valor em caps lock?? {algo.isupper()}')
print(f'{algo} é um valor em branco? {algo.isspace()}')
print(f'{algo} é possível mostrar na tela? {algo.isprintable()}')
print(f'{algo} está capitalizada? {algo.istitle()}')
